Alzado:
Magandang araw sa inyong lahat! Kami po ay narito ngayon upang talakayin ang mga mahahalagang hakbang sa paggawa ng pananaliksik, mula sa pagpili ng paksa, pagpaplano, at paggawa ng mga katanungan. Ito ang mga unang hakbang na magbibigay-direksyon sa inyong research at tutulong sa inyo upang maging mas maayos ang proseso.

Magsisimula tayo sa pagpili ng paksa, kung paano natin pipiliin ang tamang paksa para sa isang pananaliksik.

ALZADO: Pagpili ng Paksa
ALZADO:
So, una sa lahat, bakit nga ba importante ang pagpili ng paksa? Ang pagpili ng paksa ay parang pagtatanim ng binhi. Kung ang binhi ay hindi maayos, hindi ito tutubo ng maayos. Kung mali ang paksa na pipiliin mo, magiging mahirap magsimula at magpatuloy sa iyong research. Dapat malinaw at makabuluhan ang paksa para sa isang matagumpay na pananaliksik.

Page 2: Mahalagang Panuto sa Pagpili ng Paksa
ASH:
Tama, ALZADO. Ngayon, ano ang mga bagay na dapat nating isaalang-alang sa pagpili ng paksa? Unang-una, dapat ang paksa ay may Kahalagahan at Kabuluhan. Ibig sabihin, dapat may halaga ang paksa sa larangan ng iyong pag-aaral. Hindi pwedeng basta-basta lang.

Pangalawa, syempre, dapat ikaw ay may Interes sa paksa. Kung hindi ka interesado, mahihirapan kang mag-research. Mahalaga na may passion ka sa paksa na pipiliin mo.

Pangatlo, kailangan may Sapat na Impormasyon. Hindi pwede na walang available na resources o references para sa iyong paksa. Kasi, kung walang sapat na data, paano ka magsasagawa ng research?

At syempre, isaalang-alang din ang Haba ng oras na mayroon ka para magsagawa ng research. Kung may deadline na ibinigay ang guro, dapat ang paksa ay kayang tapusin sa oras na iyon.

Panghuli, huwag kalimutan ang mga Kinakailangang Gastusin. Minsan, may mga paksa na nangangailangan ng mas maraming resources, kaya't dapat ito'y isaalang-alang.

Page 5: Ang Pagpaplano
GEOFFREY:
Ngayon naman, pagkatapos mong pumili ng paksa, ano ang susunod na hakbang? Pagpaplano! Ang pagpaplano ay napaka-importante dahil dito mo pag-uusapan kung paano mo isasagawa ang iyong pananaliksik. Kung walang plano, baka magulo at walang direksyon ang iyong proyekto.

Kailangan mo munang isaalang-alang kung ano ang Istratehiya sa pagsasagawa ng iyong proyekto. Paano mo ba ito sisimulan? Ano ang mga hakbang na dapat sundin?

Pangalawa, ano-ano ang mga kakailanganing materyales? Dapat ay malinaw kung anong mga kagamitan ang kakailanganin mo, mula sa mga libro, internet resources, survey forms, at iba pa.

Huwag kalimutan din ang listahan ng mga posibleng suliranin. Dapat ay prepared ka sa mga challenges na maaaring mangyari. Halimbawa, paano kung mawalan ka ng access sa isang importanteng resource? Anong gagawin mo?

Page 6: Mga Unang Hakbang sa Pormal na Pagsasaliksik
ALZADO:
Tama, GEO]. Isa pang bagay na dapat mong tandaan ay ang mga unang hakbang sa pagsasagawa ng pormal na pananaliksik. At tulad ng sinabi natin kanina, ang pinakaunang hakbang ay ang pagpili ng tamang paksa. Kapag tama ang paksa, madali mong magagampanan ang mga susunod na hakbang ng research mo. Magiging guide mo ito mula umpisa hanggang dulo ng iyong study.

Page 7: Pagpili ng Paksa
ASH:
Oo, ang paksa talaga ay napakahalaga. Kung ang paksa mo ay hindi tiyak o malabo, magiging magulo ang buong proseso. Kaya importante na malinaw kung anong direksyon ang gusto mong tahakin. Kung ang paksa ay malinaw, magiging madali na lang ang susunod na hakbang.

Page 8: Ilang Suhestiyon sa Pagdedesisyon ng Pipiliing Paksa
Presenter 3:
Tama, ASH. Ngayon, magbibigay kami ng ilang suhestiyon sa pagpili ng paksa.

Una, iwasan ang mga napakapalasak na paksa. Huwag mong piliin yung mga paksa na madalas na pinag-uusapan. Gusto natin ng originality sa research, kaya't mas maganda kung pipili ka ng unique at interesting na paksa.

Pangalawa, iwasan ang sensitibong paksa na maaaring magdulot ng mga isyu sa karapatang pantao. Hindi magandang mag-research tungkol sa mga paksa na maaaring magdulot ng kontrobersiya o hindi pagkakaunawaan.

Pangatlo, dapat alam mo kung may sapat na oras ka upang matapos ang research mo. Huwag pipili ng paksa na mahirap tapusin sa ibinigay na time frame.

Kasama na rin dito ang sapat na mga saggunian. Tiyakin na mayroong mga resources o references na maaari mong gamitin.

Huwag kalimutan din ang napapanahong paksa. Ang paksa ay dapat relevant at may kaugnayan sa mga kasalukuyang isyu.

Page 10: Pagpapahayag ng Paksa
ALZADO:
Ngayon naman, usapan natin ang pagpapahayag ng paksa. Kung magpapahayag ka ng paksa, importante na tiyak at espisipiko ito. Mas maganda kung ang paksa mo ay isang bagay na maaari mong pagtuunan ng pansin nang buo, kesa sa isang malawak na paksa.

Halimbawa, kung ang paksa mo ay "Ang mga aktibidad ng mga mag-aaral," pwede mong gawing mas espesipiko na “Ang mga aktibidad ng mga mag-aaral ng Grade 11 sa National Christian Life College.” Kapag tiyak ang paksa, magiging mas organisado ang iyong research.

Page 11: Pangkalahatang Paksa vs. Ispesipikong Paksa
ASH:
Kagaya ng sinabi ko, isang halimbawa ng pangkalahatang paksa ay "ang mga aktibidad ng mga mag-aaral." Samantalang ang ispesipikong paksa ay ang “ang mga aktibidad ng mga mag-aaral ng Grade 11 sa National Christian Life College.” Kung mas tiyak ang paksa, mas magiging madali ang paghahanap ng mga kasagutan sa mga tanong ng iyong research.

Page 12: Pagbuo ng Katanungan sa Pananaliksik
GEO:
Sa huli, kailangan natin ng mga katanungan sa pananaliksik. Ang mga tanong na ito ang magbibigay daan sa iyong pag-aaral. Kailangan mong magtanong ng mga tiyak na katanungan na tutulong mag-guide sa iyo. Halimbawa, “Ano ang mga ginagawa ng mga ICT students?” o “Ano ang mga karanasan ng mga ICT students sa paaralan?” Ang mga katanungang ito ay magsisilbing gabay at magiging batayan sa iyong pagsusuri.

Wakas:
ALZADO:
Kaya sa kabuuan, ang pagpili ng tamang paksa, pagpaplano, at paggawa ng mga katanungan ay mga hakbang na magbibigay gabay sa atin sa paggawa ng isang mas mahusay na pananaliksik. Sana po ay may natutunan kayo mula sa mga diskusyong ito at magamit ninyo ang mga hakbang na ito sa inyong sariling mga proyekto.

ASH:
Maraming salamat po at sana ay naging makabuluhan ang aming presentasyon.